version: "2"

services:
  web:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://tweetapp:2609@postgres/tweet
      PORT: 3000
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: "tweetapp"
      POSTGRES_PASSWORD: "2609"
      POSTGRES_DB: tweet
